site_name: LiWE3 Documentation

theme: material

markdown_extensions:
    - toc:
        permalink: True

nav:
  - index.md
  - LiWE3:
    - 'Introduction': liwe3/index.md
    - NodeJS:
      - 'Library': liwe3/nodejs/index.md
      - 'Sending emails': liwe3/nodejs/send_emails.md
  - Docs2Rest:
    - 'Introduction': docs2rest/index.md
    - 'GUI Definition': docs2rest/gui.md
    - 'Menu Creation': docs2rest/menu.md
