site_name: LiWE3 Documentation

theme:
  name: material
  features:
    - content.code.annotate # (1)
  custom_dir: overrides

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - toc:
      permalink: True


nav:
  - index.md
  - LiWE3:
    - 'Introduction': liwe3/index.md
    - NodeJS:
      - 'Library': liwe3/nodejs/index.md
      - 'Sending emails': liwe3/nodejs/send_emails.md
    - NextJS:
      - 'Authentication': liwe3/nextjs/authentication.md
      - 'Payments': liwe3/nextjs/payments.md
      - 'Redux': liwe3/nextjs/redux.md
    - Tools:
      - 'Introduction': liwe3/tools/index.md
      - Docs2Rest:
        - 'Introduction': liwe3/tools/docs2rest/index.md
        - 'GUI Definition': liwe3/tools/docs2rest/gui.md
        - 'Menu Creation': liwe3/tools/docs2rest/menu.md
