site_name: LiWE3 Documentation

theme: material

markdown_extensions:
    - toc:
        permalink: True

nav:
  - index.md
  - Docs2Rest:
    - 'Introduction': docs2rest/index.md
    - 'GUI Definition': docs2rest/gui.md
